### ISSUE TITLE
No issue just a Thank You

### ISSUE THREAD

**Issue by chrismalek** [RicardoNiepel/C4-PlantUML#14]
I stumbled on this because of a link from https://kroki.io/ 

You are doing stuff with PlantUML that I had no idea was possible despite me spending a lot of time looking at the docs.  I have been using PlantUML in my tech documents for a year or so and I love it but you are bringing some stuff in the includes to a whole other level.  

Thank you!!!!

**Comment by chrismalek** [comment]
Closing...because not a real issue.

**Comment by RicardoNiepel** [comment]
Thank you! It's a pleasure to build something useful for a whole community.

Regarding what's possible:
A couple of hours ago I published Azure-PlantUML v2.0 - take a look at the Simplified mode.
I'm thinking about also making this possible for C4-PlantUML. 

https://github.com/RicardoNiepel/Azure-PlantUML/blob/master/README.md#simplified-mode
