### ISSUE TITLE
Enhance the look of Person (actor)

### ISSUE THREAD

**Issue by haakoo** [RicardoNiepel/C4-PlantUML#15]
This projects is just what I need now, after getting stuck using [Structurizr.Net](https://github.com/structurizr/dotnet) to generate PlantUML.

There just one thing, the look of `Person` (`Actor` in PlantUML) which leave something to be desired. Would it be possible to either use the `Actor` element from `PlantUML` or modify the shape to look more like the shape used by Simon Brown in C4?

Do you have any plans to continue to enhance the look of the generated diagrams?

**Comment by coldacid** [comment]
Unfortunately, PlantUML doesn't support custom shapes and probably never will. You can override the `Person` and `Person_Ext` macros to use the `actor` shape but even styled it leaves much to be desired in the output; I tried it a couple times and the results were unappealing compared to just using rectangles.

As for generating C4-PlantUML output with the Structurizr .NET libraries, you might be interested in https://gist.github.com/coldacid/465fa8f3a4cd3fdd7b640a65ad5b86f4 which is a writer for workspaces and individual views using C4-PlantUML.

**Comment by haakoo** [comment]
I see, I'll stick with this for now then.

Another quick question, shouldn't the files be `.iuml` or have I misunderstood the difference between between the file endings?

**Comment by coldacid** [comment]
If you look at `WriteProlog()` and `WriteEpilog()` in `PlantUMLWriterBase` you'll see that it does emit the `@startuml` and `@enduml` tags for each diagram. As for file extension, PlantUML honestly doesn't care and will parse out diagrams from any text files with those tags. `.puml` is pretty normal for standalone diagrams though, with `.pinc` or `.iuml` for included files.

**Comment by haakoo** [comment]
I was thinking of `C4.puml` and the three other files in this repo.

Anyway, closing this as it's not much we can do before PlantUML changes.

**Comment by ccll** [comment]
You could just put a PlantUML sprite icon in Person rectangle like this:
```
!include <C4/C4_Container>
!include <awslib/AWSCommon>
!include <awslib/General/Users>
...
Person(user, "Users\n\n<$Users,color=white>\n\nUsers of our system")
...
```

![image](https://user-images.githubusercontent.com/5366582/88502971-c7463300-d002-11ea-80b9-a28c689622de.png)
