### ISSUE TITLE
C4-PlantUML no longer works since PlantUML 1.2019.6

### ISSUE THREAD

**Issue by rogierschouten** [RicardoNiepel/C4-PlantUML#18]
The LAYOUT_WITH_LEGEND macro now gives a syntax error when you upgrade from PlantUML 1.2019.5 to 1.2019.6

Should I change how I use it or should the definition of the macro be changed?

**Comment by adrianvlupu** [comment]
Call it using `()` and it should work. Like `LAYOUT_WITH_LEGEND()`.
There is no other way around it since PlantUML changed their online version.

**Comment by Miopas** [comment]
> Call it using `()` and it should work. Like `LAYOUT_WITH_LEGEND()`.
> There is no other way around it since PlantUML changed their online version.

it works for me. thx!

**Comment by rogierschouten** [comment]
Works, thank you!

**Comment by Potherca** [comment]
Resolved in #29 by updating the example in the README.
