### ISSUE TITLE
Tier Application Architecture

### ISSUE THREAD

**Issue by DTHerrera** [RicardoNiepel/C4-PlantUML#41]
Hello, is it possible to generate Tier Application Architecture?, for example in FrontEnd, MiddleWare and BackEnd.

as in the following yellow image

![C4Grouping](https://user-images.githubusercontent.com/36610780/73087959-f388c780-3e98-11ea-9b7b-bb8cd8f4e682.png)

**Comment by adrianvlupu** [comment]
I guess you could use `Boundary(front, "Front End", "Tier"){` and group the **Containers** with it.

Something like:
```plantuml
@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Boundary(front, "Front End", "Tier"){
    Container(mobile, "Mobile App", "Xamarin", "description...")
    Person(customer, "A customer")
}
Boundary(middleware, "Middleware", "tier"){
    Container(mb, "Message Bus", "RabbitMQ", "description...")
    Container(customerService, "Customer Service", "java, spring boot", "description...")
    Container(customerApp, "Customer Application", "javascript, angular",  "description...")
    Container(auditService, "Audit Service", "C#, .NET", "description...")
    Container(reportingService, "Reporting Service", "Ruby", "description...")
    ContainerDb(customerDb, "Customer Database", "Oracle 12c", "Stores customer information")
}
Rel(customer, mobile, "uses")
Rel_R(customer, customerApp, "uses", "browser")
Rel_R(customerApp, customerService, "uses")
Rel_R(customerService, mb, "uses")
Rel(customerService, customerDb, "read/write")
Rel_U(auditService, mb, "read")
Rel(reportingService, mb, "read")
Boundary(backend, "Backend", "Tier"){
    Container(auditStore, "Audit Store", "event store", "description...")
    ContainerDb(reportingDB, "Reporting Database", "MySQL", "description...")
}
Rel_R(auditService, auditStore, "writes")
Rel_R(reportingService, reportingDB, "writes")
@enduml
```

![img](https://www.plantuml.com/plantuml/png/0/bLHDZzem4BtpArnwOIMQg5LFFIrV_P20tGsWjYSqJcPPjuaTZHqGglQ_xpX0FWehsbpYcNb-7Zy_-zOw85TaQUUDqd5Q95XGAfwSo-sdC2JO1HlbdWfPMAJOQ8VQ1R79maZ5G8cPAymn3KSVtzsdeDrgDWqpi0w9K-iHuq5ff23t2tIcWvztg-Nw-xVbr_LqycKo7_TkEfsXANG2jEyz4kFxellP_yL49rqEbWgfU_Ed8_Yh-7gPaIf5Bi_AWHZakGV_W0n8QJzCqCQaSgUC3eAWUrCIt2DPetjnOPt9a1Ws4AU08SzrBvbAaXHtGEKYLU2PtUMEf0UYjR11CIoiHqOWfNApXrVxgQUVkbWWRLNi5nqTC-AOyYI_O0jzONFUuqP8Ozn_CBD4JLOEKpv2F-l4VA3f2z2R8WNYz5LoA1Bbwfu7FcmsF7hR5y5yilo7FWbpGuutLjD5frIJCYha_ZhTM5OR7ylcliVWG88jgUu8OZRF-m-nZnRE4DhA3qBfHqFPGI7lZGZJXdCg1_B5i5pdwZfgrDkobo3-Ip8xMtgjZIzHvnwuo5sLIylLa7D0Im52IC8TAOT7njLVfvUTK4UwymDf8ggR8Y7-ZJhXol0mUltM7jRpCjTUyP6VWLj-MOGzXLTFj-fkF6mvfNc-i_tYONgHxVceQLk1Ld-bLBNwvsgqEwZWjom1ltOl)

**Comment by DTHerrera** [comment]
Hello, thanks for the answer. I think it's an excellent option:

Is there any way that all Boundary boxes have the same height?

**Comment by adrianvlupu** [comment]
I don't think so, this has to do with plantuml itself and graphviz. It chooses the layout for you. Found something similar on plantuml forum https://forum.plantuml.net/7619/position-and-size-alignment-of-packages-component-diagram
