### ISSUE TITLE
<<boundary>> stereotype colors/skinparams not changeable

### ISSUE THREAD

**Issue by christo-ph** [RicardoNiepel/C4-PlantUML#48]
Hi,

I am trying to manipulate the <<boundary>> stereotype font color or size, but it seems to have no effect. All other types working correctly.

No matter what I do, the stereotype remains here white and the size remains default:

![image](https://user-images.githubusercontent.com/16965068/76160576-a0f32a00-612b-11ea-9fde-ae4873a9c9d0.png)

what I currently have for styling:

```
!define BORDER_COLOR      #333333
!define FONT_COLOR        #333333

skinparam rectangle<<boundary>> {
  Shadowing false
  StereotypeFontSize 0
  StereotypeFontColor FONT_COLOR
  FontColor FONT_COLOR
  BorderColor BORDER_COLOR
  BorderStyle dashed
```

Thanks for your help.

**Comment by adrianvlupu** [comment]
There seems to be an issue with plantuml itself, maybe I'm missing something but check out this example:

```plantuml
@startuml test
skinparam rectangle<<outerbox>> {
    FontColor #FF0000
    BackgroundColor #00FF00
    StereotypeFontSize 40
}

skinparam rectangle<<box>> {
    StereotypeFontSize 40
}

rectangle "Box" <<outerbox>>{
    rectangle "Nested" <<box>>
}

rectangle "Box2" <<outerbox>>
rectangle "NotNested" <<box>>
@enduml
```

![test](https://www.plantuml.com/plantuml/png/0/TP3F2eCm38VlVOhWNg2C7KN4WKSlFa5dWuZQI4t1RUpTrtPZTFzopFVxaZRboigocoTWN5cius0MPTKC5ZjMffympyansXDjHG5N0RvgCdoaYIpiwbhwYjrATMDloHdzP5866bdh9o3nUS7WjiC5uI35JVnUcExwQxxoa5MqPP2-yw4cYSP_3dK8HVxjxzy7fBGX_jHBDDhVx0u0 "test")

The moment you nest them, the stereotype properties are ignored for the parent element. I think this is the best place to start playing with the properties and maybe you could find something that works. I tried a bunch of combinations but nothing seems to do the trick.

**Comment by christo-ph** [comment]
I am going to close this. It is PlantUML related, and according to their announcement, in favour of their new [styling system](https://plantuml.com/de/style-evolution) there will be [no further time spend on skinparam syntax](https://github.com/plantuml/plantuml/issues/255#issuecomment-531592070).

**Comment by kirchsth** [comment]
@christo-ph: the problem can be solved if you change the package<<...>> stereotype too (rectangle does not set all; details see https://github.com/plantuml-stdlib/C4-PlantUML/issues/128).

```
@startuml
!define BORDER_COLOR      #333333
!define FONT_COLOR        #770000

skinparam rectangle<<boundary>> {
  Shadowing false
  StereotypeFontSize 30
  StereotypeFontColor FONT_COLOR
  FontColor FONT_COLOR
  BorderColor BORDER_COLOR
'  BackgroundColor #00EEEE
  BorderStyle dashed
}

' skinparam package<<boundary>> {
'   StereotypeFontSize 30
'   StereotypeFontColor FONT_COLOR
'}

rectangle "Box" <<boundary>>{
    rectangle "Nested" <<boundary>>
}

rectangle "NotNested" <<boundary>>
@enduml
```

![](http://www.plantuml.com/plantuml/png/TP4nRy9038Nt-nKk3AoH65WGGg4mLOcKTAzSpeI8S1VvZDeKzR_NW1IEjdcZt_VilDmo2BASZervihIh7K6Q5y_hucsLl-G5N3MUNjKJcpnxZNqbPhD4PKmurAv5nYCmRGLTrT1y_kvFpY9tYmMS3K2vH-i_QbV13fj0buaGavUkfOrtKjPV1DFaptpb6y_HSGK6ngbdItmpuZfceXvk3nLVlkZcZvDahUfJfNGDWSMm9sk-ZKRkdLhDOlMhaH833UxES8U9dkX_5OnI_pc2UF_PW2eYCWf2zX4oZqioB_zIIt9MN_e7) 

```
@startuml
!define BORDER_COLOR      #333333
!define FONT_COLOR        #770000

skinparam rectangle<<boundary>> {
  Shadowing false
  StereotypeFontSize 30
  StereotypeFontColor FONT_COLOR
  FontColor FONT_COLOR
  BorderColor BORDER_COLOR
'  BackgroundColor #00EEEE
  BorderStyle dashed
}

' that all boundaries have the same init color as the normal rectangle
' (but as soon you change the rectangle background color the package background color is updated too
' and you don't need to set the color in plantUML context)
skinparam packageBackgroundColor #FEFECE

skinparam package<<boundary>> {
   StereotypeFontSize 30
   StereotypeFontColor FONT_COLOR
}

rectangle "Box" <<boundary>>{
    rectangle "Nested" <<boundary>>
}

rectangle "NotNested" <<boundary>>
@enduml
```

![](http://www.plantuml.com/plantuml/png/XL2nJiCm5Dpz5OzsO8tKeKjLLIt9X1gfOKUF-3MnwjYH_G84nB_ZfYWOGiMDT-VplTjuHiTTeyMDfACo1DlyS9SU7dVvVNw00VF5WD6HvVk7M0-EvJ894CAVb6dHOGEEIaPJQLgjdcnd9Bf-lOPt0L3KAEsBCXKSKNiwCqoEBFSjPTPmeTu85ic4trbjNVHvC5oXjzP9SXSXFaVS1WtBK-NEZIxwF4dIWF5LmRqcaEXhak93X2TS8mDg3LztAF9GupC5WS1ZGw2COYY7EFG3RQnhK7-F40tJXW9OqQH7bcRfBXKJvsJ0gtlzErWuPsm4iwrzdK4SFcH3vDYJPv8_JRz2zfR_T6t8oAxHdm00)

BR Helmut
